name: Build chat_client.exe only

on:
  push:
    tags:
      - '*'  # 每次 push tag（v1.0.0 等）就自動執行

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build EXE from chat_client.py
        run: pyinstaller --onefile chat_client.py

      - name: Upload chat_client.exe to Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/chat_client.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
