name: Build chat_client.exe for Windows

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Build EXE
        run: pyinstaller --onefile chat_client.py

      - name: Upload EXE to Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/chat_client.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
